### ISSUE TITLE
Initiating shutdown

### ISSUE THREAD

**Issue by haryngod** [captain-yoshi/moveit_benchmark_suite#90]
I tried to run motion_planning_pp.launch with default parameters.
It shown lots of 'Only joint-space goals are supported' errors, then it shutdown with below message.

```bash
================================================================================REQUIRED process [benchmark-2] has died!
process has died [pid 7774, exit code -11, cmd /home/kang/rb_ws/devel/lib/moveit_benchmark_suite/motion_planning_pp __name:=benchmark __log:=/home/kang/.ros/log/efb0ed96-63ba-11ed-9254-49fc91180687/benchmark-2.log].
log file: /home/kang/.ros/log/efb0ed96-63ba-11ed-9254-49fc91180687/benchmark-2*.log
Initiating shutdown!
================================================================================
```

**Comment by captain-yoshi** [comment]
The default [config](moveit/config/motion_planning_pp.yaml) is not well formed. It only tests for the CHOMP planner which does not accept cartesian goals. In the meantime, you can comment the CHOMP pipeline and uncomment the ompl pipeline.

I will update the config tomorow. Thank you for reporting the bug!

**Comment by haryngod** [comment]
It works with ompl pipeline.
Thank you for your quick reply :)
