### ISSUE TITLE
'InfXXX' planners are read as a Double

### ISSUE THREAD

**Issue by haryngod** [captain-yoshi/moveit_benchmark_suite#94]
I'am trying to apply my custom planner.
I already put my planners in moveit.
But when I launch benchmark, my planner id is read as a Double type instead String.
Do I need to do some steps for this?

**Comment by haryngod** [comment]
I guess this is the parser bug.
My custom planner name start with 'Inf'.
I think, during the parsing, parser thinks it is double type.
I tested with Inftest which is for testing. And planner_configs parameters like as below(The second planner is Inftest).

```
rosparam get /planning_pipelines/ompl/all_arms/planner_configs
- AnytimePathShortening
- .inf
- SBL
- EST
- LBKPIECE
- BKPIECE

```

**Comment by captain-yoshi** [comment]
> I guess this is the parser bug.

Yup this is a bug from a third party library used by the parser (https://github.com/fastfloat/fast_float/issues/164).

OMPL caught the issue:
``` bash
[ERROR] [1672198766.163045331]: Planner configuration names must be of type string (for group 'hand')
```

In the meantime, you can change the planner that starts with a `Inf` with something else. Will let this issue open until a fix is implemented. Thanks for reporting this !

**Comment by captain-yoshi** [comment]
Should be fixed with the newest update of the [parser](https://github.com/captain-yoshi/moveit_serialization).
